<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\achievements.png" />
    <None Remove="Assets\cards.png" />
    <None Remove="Assets\logo-black.png" />
    <None Remove="Assets\logo.png" />
    <None Remove="Assets\settings.png" />
    <None Remove="Assets\tests.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\achievements.png" />
    <Resource Include="Assets\cards.png" />
    <Resource Include="Assets\logo-black.png" />
    <Resource Include="Assets\logo.png" />
    <Resource Include="Assets\settings.png" />
    <Resource Include="Assets\tests.png" />
  </ItemGroup>
<ItemGroup>
  <ProjectReference Include="..\BrainBurst.BLL\BrainBurst.BLL.csproj" />
  <ProjectReference Include="..\BrainBurst.DAL\BrainBurst.DAL.csproj" />
</ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
